#!/usr/bin/env python3
"""Generates guidelines.js from guidelines-import.csv. Run after any CSV edit."""

import csv
import json
import sys
from pathlib import Path

INPUT  = Path(__file__).parent / "guidelines-import.csv"
OUTPUT = Path(__file__).parent / "guidelines.js"

REQUIRED_COLS = {
    "Condition", "Body Region", "Body Region Display",
    "Issuing Organization", "Publication Date", "Guideline URL",
    "Key Recommendations", "Notes",
}

def abort(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)

def warn(msg):
    print(f"WARNING: {msg}", file=sys.stderr)

def main():
    if not INPUT.exists():
        abort(f"{INPUT} not found")

    rows = []
    seen_urls = {}

    with open(INPUT, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        missing = REQUIRED_COLS - set(reader.fieldnames or [])
        if missing:
            abort(f"CSV missing columns: {missing}")

        for i, row in enumerate(reader, start=2):  # row 1 is header
            url = row["Guideline URL"].strip()
            if not url:
                warn(f"Row {i}: empty URL — skipping")
                continue

            if url in seen_urls:
                abort(
                    f"Duplicate URL on rows {seen_urls[url]} and {i}: {url}\n"
                    "If this is intentional, remove the duplicate row."
                )
            seen_urls[url] = i

            rows.append({
                "condition":        row["Condition"].strip(),
                "bodyRegion":       row["Body Region"].strip().lower(),
                "bodyRegionDisplay":row["Body Region Display"].strip(),
                "issuingOrg":       row["Issuing Organization"].strip(),
                "publicationDate":  row["Publication Date"].strip(),
                "url":              url,
                "keyRecommendations": row["Key Recommendations"].strip(),
                "notes":            row["Notes"].strip(),
            })

    js = (
        "// AUTO-GENERATED by generate-guidelines.py — do not edit manually.\n"
        f"// Source: guidelines-import.csv ({len(rows)} guidelines)\n\n"
        "const guidelines = " + json.dumps(rows, indent=2, ensure_ascii=False) + ";\n"
    )

    OUTPUT.write_text(js, encoding="utf-8")
    print(f"OK: wrote {len(rows)} guidelines to {OUTPUT.name}")

if __name__ == "__main__":
    main()
