// AUTO-GENERATED by generate-guidelines.py — do not edit manually.
// Source: guidelines-import.csv (3 guidelines)

const guidelines = [
  {
    "condition": "Carpal Tunnel Syndrome",
    "bodyRegion": "wrist",
    "bodyRegionDisplay": "Wrist/Hand",
    "issuingOrg": "APTA Orthopedics",
    "publicationDate": "2026",
    "url": "https://www.orthopt.org/uploads/content_files/files/Hand_Pain_CTS_jospt.2026.0301_new.pdf",
    "keyRecommendations": "Use Phalen test, Tinel sign, and carpal compression (Durkan) test for diagnosis; Semmes-Weinstein monofilaments for sensory threshold. Recommend neutral wrist orthosis worn at night for mild-moderate CTS (nonsurgical management or awaiting surgery). Manual therapy to cervical spine and upper extremity may provide short-term pain and function improvement. Avoid iontophoresis/phonophoresis with corticosteroids. Kinesiology taping, therapeutic exercise (orthotic/stretching), and laser therapy may offer short-term benefit for mild-moderate CTS.",
    "notes": "2026 revision of JOSPT CPG; published J Orthop Sports Phys Ther 2026;56(4):CPG1-CPG79. Doi: 10.2519/jospt.2026.0301. From APTA Orthopedics and APTA Hand and Upper Extremity Academies."
  },
  {
    "condition": "Hip Osteoarthritis",
    "bodyRegion": "hip",
    "bodyRegionDisplay": "Hip",
    "issuingOrg": "APTA Orthopedics",
    "publicationDate": "2025",
    "url": "https://www.orthopt.org/uploads/content_files/files/koc_et_al_2025_hip_pain_and_mobility_deficits_hip_osteoarthritis_revision_2025%281%29.pdf",
    "keyRecommendations": "Manual therapy (joint mobilization, long-axis hip distraction) strongly recommended for mild-moderate hip OA to increase ROM, decrease pain, and improve function. Individualized exercise program (including aquatic therapy) 1-5x/week for 5-16 weeks strongly recommended. Dry needling to iliopsoas, rectus femoris, TFL, gluteus medius/minimus for short-term pain and function improvements. Patient education on activity modification, exercise, and weight reduction. Functional, gait, and balance training including assistive device instruction. Do not use bracing as first-line treatment.",
    "notes": "2025 revision (third CPG; updates 2009 and 2017 versions). Published J Orthop Sports Phys Ther 2025;55(11):CPG1-CPG31. doi:10.2519/jospt.2025.0301. From APTA Orthopedics and APTA Academy of Sports Physical Therapy. Next review 2030."
  },
  {
    "condition": "Midportion Achilles Tendinopathy",
    "bodyRegion": "ankle",
    "bodyRegionDisplay": "Ankle/Foot",
    "issuingOrg": "APTA Orthopedics",
    "publicationDate": "2024",
    "url": "https://www.orthopt.org/uploads/content_files/files/Achilles_Pain_revision_2024.pdf",
    "keyRecommendations": "Tendon loading exercise (loads as high as tolerated) is first-line treatment to improve function and decrease pain; exercise ≥3x/week at maximum tolerated intensity. Provide patient education/counseling (pain science or pathoanatomic focus) combined with loading exercise — in-person or via telehealth. Advise against complete rest; continue activities within pain tolerance. Manual therapy (mobilization of muscles, joints, connective tissue) for those with mobility deficits. Intramuscular dry needling to calf for muscle pain/stiffness, especially in acute cases. Heel lifts may temporarily reduce dorsiflexion loading. No recommendation for orthoses (contradictory evidence). Elastic or rigid taping may reduce pain or decrease tendon strain. Do not use low-level laser therapy or therapeutic ultrasound alone.",
    "notes": "2024 revision (third CPG; updates 2018 and 2010 versions). Published J Orthop Sports Phys Ther 2024;54(12):CPG1-CPG32. Epub 27 November 2024. doi:10.2519/jospt.2024.0302. From APTA Orthopedics (AOPT). Focused on midportion Achilles tendinopathy only; insertional Achilles tendinopathy excluded. ESWT considered outside PT scope for this update."
  }
];
