// AUTO-GENERATED by generate-guidelines.py — do not edit manually.
// Source: guidelines-import.csv (1 guidelines)

const guidelines = [
  {
    "condition": "Carpal Tunnel Syndrome",
    "bodyRegion": "wrist",
    "bodyRegionDisplay": "Wrist/Hand",
    "issuingOrg": "APTA Orthopedics",
    "publicationDate": "2026",
    "url": "https://www.orthopt.org/uploads/content_files/files/Hand_Pain_CTS_jospt.2026.0301_new.pdf",
    "keyRecommendations": "Use Phalen test, Tinel sign, and carpal compression (Durkan) test for diagnosis; Semmes-Weinstein monofilaments for sensory threshold. Recommend neutral wrist orthosis worn at night for mild-moderate CTS (nonsurgical management or awaiting surgery). Manual therapy to cervical spine and upper extremity may provide short-term pain and function improvement. Avoid iontophoresis/phonophoresis with corticosteroids. Kinesiology taping, therapeutic exercise (orthotic/stretching), and laser therapy may offer short-term benefit for mild-moderate CTS.",
    "notes": "2026 revision of JOSPT CPG; published J Orthop Sports Phys Ther 2026;56(4):CPG1-CPG79. Doi: 10.2519/jospt.2026.0301. From APTA Orthopedics and APTA Hand and Upper Extremity Academies."
  }
];
